name: open_authenticator
description: A cross-platform OTP app, free and open-source.
publish_to: none
version: 1.4.2+23
homepage: https://openauthenticator.app
repository: https://github.com/Skyost/OpenAuthenticator
issue_tracker: https://github.com/Skyost/OpenAuthenticator/issues
funding:
  - https://ko-fi.com/Skyost
  - https://paypal.me/Skyost

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.1.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter_riverpod: ^3.0.3
  simple_secure_storage: ^0.3.6
  jovial_svg: ^1.1.28
  mobile_scanner: ^7.1.3
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  webcrypto: ^0.5.8
  equatable: ^2.0.7
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path: ^1.9.1
  local_auth: ^3.0.0
  package_info_plus: ^9.0.0
  http: ^1.6.0
  qr_flutter: ^4.1.0
  intl: any
  url_launcher: ^6.3.2
  firebase_app_check: ^0.4.1
  purchases_flutter: ^9.9.6
  purchases_ui_flutter: ^9.9.6
  firebase_crashlytics: ^5.0.4
  window_manager: ^0.5.1
  slang: ^4.10.0
  slang_flutter: ^4.10.0
  rate_my_app: ^2.3.2
  app_links: ^6.4.1
  hashlib: ^2.2.0
  hashlib_codecs: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.1
  wakelock_plus: ^1.4.0
  file_picker: ^10.3.6

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  drift_dev: ^2.29.0
  msix: ^3.16.12
  slang_build_runner: ^4.10.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  release: ^0.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/authentication/
    - assets/images/intro/

msix_config:
  display_name: Open Authenticator
  publisher_display_name: Skyost
  identity_name: 32411Skyost.OpenAuthenticator
  publisher: CN=13F97469-F5E7-4417-A3EC-E47287736FE3
  store: true
  logo_path: windows/msix.png
  languages: en, fr, de, pt, it
  trim_logo: false
  capabilities: internetClientServer
  protocol_activation: otpauth

release:
  changelog:
    header: '# ðŸ“° Open Authenticator changelog'
